version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - tickets

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tickets

  db:
    image: mysql:8.4.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_USER: tickets
      MYSQL_PASSWORD: tickets
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - tickets

  composer:
    image: composer:2
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["composer"]

networks:
  tickets:

volumes:
  mysqldata: